app.py
from flask import Flask,session
from flask_session import Session

app = Flask(__name__)
from app_blueprint import app_blueprint


app.config["SESSION_PERMANENT"] = False
app.config["SESSION_TYPE"] = "filesystem"
Session(app)
app.register_blueprint(app_blueprint)

app_blueprint.py
from flask import Blueprint, render_template,request,jsonify,session
from flask_session import Session

app_blueprint = Blueprint('app_blueprint',__name__)
first_name = ""

#variables
popular_products = [
    {'name':'Johan','size':'small','price':5,'img':'/img/rome.jpg'},
    {'name':'Robert','size':'med','price':6,'img':'/img/rome.jpg'},
    {'name':'David','size':'large','price':7,'img':'/img/rome.jpg'}
]

@app_blueprint.route('/')
def index():
        #return "<h1>Homepage2<h1>"
        return render_template("index.html",popular_products=popular_products)

@app_blueprint.route('/about5')
def about3():
        #return "<h1>Homepage2<h1>"
        return render_template("about.html",first_name=first_name)


@app_blueprint.route('/contact')
def contact():
        #return "<h1>Homepage2<h1>"
        return render_template("contact.html")

# A decorator used to tell the application
# which URL is associated function
@app_blueprint.route('/nameForm', methods =["GET", "POST"])
def nameForm():
    if request.method == "POST":
       # getting input with name = fname in HTML form
       first_name = request.form.get("fname")
       # getting input with name = lname in HTML form
       last_name = request.form.get("lname")

       session["full_name"] = first_name + " "  + last_name

       #return "Your name is "+first_name + last_name
       return render_template("about.html",first_name=first_name)
    return render_template("name_form.html")

@app_blueprint.route('/process',methods=['POST'])   
def process():
        email = request.form['email']
        name = request.form['name']

        if name and email:
                newName = name[::-1]
                return jsonify({'name' : newName})
        return jsonify({'error': 'Missing data'})        


@app_blueprint.route('/nameFormAjax')
def nameFormAjax():
        #return "<h1>Homepage2<h1>"
        return render_template("name_form-ajax.html")    

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <title>About us</title>
    </head>

    <body>
        <!-- call about.html file-->
        <a href="{{url_for('app_blueprint.index')}}">about us</a>

        <p>Hello {{first_name}}</p>
        <center><h1>About us</h1></center>
        <center><p>We sell fast</p></center>
        <br>
        {% if session.full_name %}
            You are Registered {{ session.full_name }} .
        {% else %}
            You are not Registered..
        {% endif %}

    </body>


</html>

templates/contact.html
<!DOCTYPE html>
<html>
    <head>
        <title>Contact us</title>
    </head>

    <body>
        <center><h1>Contact us</h1></center>
        <center><p>Contact</p></center>
    </body>


</html>

templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>My website</title>
        <link rel="stylesheet" href ="{{url_for('static',filename='/css/index.css')}}"
    </head>

    <body>
        <!-- call css file-->
        <center><h1 class="test">Roberts storeb</h1></center>

        <!-- call about.html file-->
        <a href="{{url_for('app_blueprint.about3')}}">about us</a>
        <a href="{{url_for('app_blueprint.nameForm')}}">Name Form</a>
        <a href="{{url_for('app_blueprint.nameFormAjax')}}">Name Form Ajax</a>

        <center><p>Best merch in the buiness</p></center>

        <!--show image-->
        <img src= "{{url_for('static',filename='/img/Great.jpeg')}}"
        <center><p>Popular products</p></center>

        <!--loop-->
        {% for product in popular_products %}
           <h3>Product Name: {{product.name}} </h3>
           <h3>Product size: {{product.size}} </h3>
           <img src= "{{url_for('static',filename=product.img)}}"
        {% endfor %}


    </body>


</html>

templates/name_form-ajax.html
<!DOCTYPE html>

<html>
<head>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
    <script src="{{ url_for('static', filename='js/form.js') }}"></script>

</head>

<form>
    <label for="email">Email:</label>
    <input type="text" id="emailInput" name="email" placeholder="email">
    <label for="lastname">Last Name:</label>
    <input type="text" id="nameInput" name="lname" placeholder="lastname">
    <button type="submit">Submit</button>

    

</form>
<div id="successAlert" style="display:none"><</div>
<div id="errorAlert" style="display:none"><</div>

<a href="{{url_for('app_blueprint.about3')}}">about us</a>

</html>

templates/name_form.html
<form action="{{ url_for("app_blueprint.nameForm")}}" method="post">
    <label for="firstname">First Name:</label>
    <input type="text" id="firstname" name="fname" placeholder="firstname">
    <label for="lastname">Last Name:</label>
    <input type="text" id="lastname" name="lname" placeholder="lastname">
    <button type="submit">Login</button>

    <a href="{{url_for('app_blueprint.about3')}}">about us</a>